name: simpletodolist
description: simpleTodoList from Figma design

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: 1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^4.0.3
  intl: 0.18.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/prof.png
    - assets/svg/search_icon.svg
    - assets/svg/calendar.svg

